#!/usr/bin/env node
/* eslint-env node */
'use strict';
var async = require('async');
var fs = require('fs');
var path = require('path');
var gp = require('geojson-precision');
var beautify = require('js-beautify');

async.each(fs.readdirSync(path.resolve(__dirname, '../protectorates')), function(file, done) {
	file = path.resolve(__dirname, '../protectorates', file);

	fs.readFile(file, function(err, data) {
		if (err) {
			done(err);
			return;
		}

		var json = JSON.parse(data);
		var trimmed = gp.parse(json, 3);

		fs.writeFile(file, beautify(JSON.stringify(trimmed), {
			'indent_with_tabs': true,
			'brace_style': 'end-expand'
		}), done);
	});
});
